from send_error import  SendException
ex=SendException()
ex.send_exception()